#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Resolve the repo root from this script's own location, so it works no
# matter what directory you run it from.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$REPO_ROOT/js/config.js"
ENV_FILE="${TMPDIR:-/tmp}/.bde-google-sheets-wizard.env"

banner "Connect the BDE contact form to Google Sheets"

# ── Stage 1: create the spreadsheet ────────────────────────────────────────
stage "Create the spreadsheet"
say "This is where every contact-form enquiry and email-capture lead will land."
open_url "https://docs.google.com/spreadsheets/create"
step "Rename it (click 'Untitled spreadsheet', top-left) to something like 'BDE Website Enquiries'."
step "In row 1, add these column headers: Timestamp | Name | Email | Phone | Service | Company | Message"
pause "Done renaming it and adding the header row?"

# ── Stage 2: paste the Apps Script receiver ────────────────────────────────
stage "Add the receiver script"
ask NOTIFY_EMAIL "Which email should receive enquiry notifications? [Enter for shahfiqnashrah@gmail.com]:"
NOTIFY_EMAIL="${NOTIFY_EMAIL:-shahfiqnashrah@gmail.com}"
write_env NOTIFY_EMAIL "$NOTIFY_EMAIL"

say "This script appends every submission as a new row and emails $NOTIFY_EMAIL."
step "In the spreadsheet, go to Extensions → Apps Script (opens a new tab)."
pause "Opened Extensions → Apps Script?"
step "Delete anything already in Code.gs, then paste everything between the lines below:"
printf '\n%s────────────────────────── copy from here ──────────────────────────%s\n' "$DIM" "$RESET"
cat <<APPSSCRIPT
function doPost(e) {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var p = e.parameter;

  // Honeypot: a real visitor never fills this hidden field in. If it's
  // filled, quietly pretend success without writing anything or emailing.
  if (p.botcheck) {
    return ContentService.createTextOutput(JSON.stringify({ result: "success" }))
      .setMimeType(ContentService.MimeType.JSON);
  }

  sheet.appendRow([
    new Date(),
    p.name || "",
    p.email || "",
    p.phone || "",
    p.service || "",
    p.company || "",
    p.message || ""
  ]);

  MailApp.sendEmail({
    to: "$NOTIFY_EMAIL",
    subject: "New enquiry — " + (p.service || "General") + " — " + (p.name || ""),
    body:
      "New website enquiry:\n\n" +
      "Name: " + (p.name || "") + "\n" +
      "Email: " + (p.email || "") + "\n" +
      "Phone: " + (p.phone || "") + "\n" +
      "Service: " + (p.service || "") + "\n" +
      "Company: " + (p.company || "") + "\n\n" +
      "Message:\n" + (p.message || "")
  });

  return ContentService.createTextOutput(JSON.stringify({ result: "success" }))
    .setMimeType(ContentService.MimeType.JSON);
}
APPSSCRIPT
printf '%s─────────────────────────── copy to here ───────────────────────────%s\n\n' "$DIM" "$RESET"
step "Click the Save icon (or Ctrl+S / Cmd+S). Name the project 'BDE Enquiry Handler' if it asks."
pause "Pasted and saved?"

# ── Stage 3: deploy as a Web App ───────────────────────────────────────────
stage "Deploy it as a Web App"
say "This turns the script into a URL the website can submit form data to."
step "Click Deploy → New deployment."
step "Click the gear icon next to 'Select type' and choose Web app."
step "Set Execute as: Me, and Who has access: Anyone."
step "Click Deploy."
step "Click Authorize access, then pick your Google account."
warn "If you see \"Google hasn't verified this app\", that's expected for your own script — click Advanced → Go to [project name] (unsafe)."
step "Copy the Web app URL shown (it ends in /exec)."
ask SHEETS_URL "Paste the Web app URL here:"
write_env SHEETS_URL "$SHEETS_URL"

# ── Stage 4: wire the URL into the site ────────────────────────────────────
stage "Wire it into the website"
say "Updating js/config.js with the URL you just copied."
if [[ ! -f "$CONFIG_FILE" ]]; then
  warn "Couldn't find $CONFIG_FILE — paste this in by hand: $SHEETS_URL"
  SKIPPED+=("paste $SHEETS_URL into js/config.js manually (file not found)")
elif ! grep -q "googleSheetsFormUrl" "$CONFIG_FILE"; then
  warn "Couldn't find a googleSheetsFormUrl line in $CONFIG_FILE — paste this in by hand: $SHEETS_URL"
  SKIPPED+=("paste $SHEETS_URL into js/config.js manually (key not found)")
else
  sed -i.bak "s|googleSheetsFormUrl: \"[^\"]*\"|googleSheetsFormUrl: \"$SHEETS_URL\"|" "$CONFIG_FILE"
  rm -f "$CONFIG_FILE.bak"
  printf '  %s✓ updated%s googleSheetsFormUrl in js/config.js\n' "$GREEN" "$RESET"

  if command -v git >/dev/null 2>&1 && git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    if git -C "$REPO_ROOT" diff --quiet -- js/config.js; then
      note "No changes to commit (this URL may already be set)."
    else
      printf '\n'
      git -C "$REPO_ROOT" diff -- js/config.js
      if confirm "Commit and push this change now? (GitHub Pages will rebuild)"; then
        git -C "$REPO_ROOT" add js/config.js
        git -C "$REPO_ROOT" commit -m "Connect contact form to Google Sheets" >/dev/null
        git -C "$REPO_ROOT" push
        printf '  %s✓ pushed%s — GitHub Pages should rebuild within a minute or two.\n' "$GREEN" "$RESET"
      else
        SKIPPED+=("commit + push js/config.js (left as an uncommitted change)")
      fi
    fi
  else
    SKIPPED+=("commit + push js/config.js (not a git repo, or git not installed)")
  fi
fi

# ── Stage 5: test it end-to-end ────────────────────────────────────────────
stage "Test it end-to-end"
say "Confirm the whole loop actually works before relying on it."
open_url "https://shahfiqnashrah-blip.github.io/bitara-digital-enterprise-website/contact.html"
step "Submit the contact form with a test name, email, and message."
step "Check the Google Sheet — a new row should appear."
step "Check $NOTIFY_EMAIL — a notification email should arrive."
if confirm "Did the row appear and the email arrive?"; then
  note "Fully wired up."
else
  warn "Common fixes: deployment access must be 'Anyone' (not 'Anyone with a Google account'), and you must click Deploy (not just Save) after any script change — Manage deployments → edit → New version."
  SKIPPED+=("re-check the Apps Script deployment settings — test submission didn't come through")
fi

finish
